export enum ProviderKey {
	Antigravity = "antigravity",
	Chutes = "chutes",
	Codex = "codex",
	DeepInfra = "deepinfra",
	DeepSeek = "deepseek",
	GeminiCli = "geminicli",
	Huggingface = "huggingface",
	Kimi = "kimi",
	Mistral = "mistral",
	MiniMax = "minimax",
	MiniMaxCoding = "minimax-coding",
	Moonshot = "moonshot",
	OpenCode = "opencode",
	OpenAI = "openai",
	QwenCli = "qwencli",
	Zenmux = "zenmux",
	Zhipu = "zhipu",
	Compatible = "compatible",
}
